# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /source
COPY . .

# Restore dependencies
RUN dotnet restore "./Core/Core.csproj" --disable-parallel
RUN dotnet restore "./DAL/DAL.csproj" --disable-parallel
RUN dotnet restore "./BLL/Bll.csproj" --disable-parallel
RUN dotnet restore "./TestApplicationServer/TestApplicationServer.csproj" --disable-parallel

# Publish the application
RUN dotnet publish "./Core/Core.csproj" -c release -o /core --no-restore
RUN dotnet publish "./DAL/DAL.csproj" -c release -o /dal --no-restore
RUN dotnet publish "./BLL/Bll.csproj" -c release -o /bll --no-restore
RUN dotnet publish "./TestApplicationServer/TestApplicationServer.csproj" -c release -o /app --no-restore

# Stage 2: Create the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal
WORKDIR /app

# Copy the published artifacts from the build stage
COPY --from=build /core ./core
COPY --from=build /dal ./dal
COPY --from=build /bll ./bll
COPY --from=build /app ./app

# Expose port 5000
EXPOSE 5000

# Set the entry point for the application
ENTRYPOINT ["dotnet", "./app/TestApplicationServer.dll"]
